import { initializeApp } from "firebase/app";
import { getFirestore, collection, doc, setDoc, getDoc, getDocs, deleteDoc, query, orderBy, getDocFromServer, where, limit } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import { InterviewSession, UserProfile } from "../types";
import firebaseConfig from "../../firebase-applet-config.json";

// Initialize Firebase using the configuration generated by set_up_firebase
const app = initializeApp(firebaseConfig);

// Initialize Firestore with specific database ID (CRITICAL: The app will break without this database ID)
const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
const auth = getAuth(app);

export { db, auth };

// Firestore Connection Validation Check
async function testConnection() {
  try {
    await getDocFromServer(doc(db, "test", "connection"));
  } catch (error) {
    if (error instanceof Error && error.message.includes("the client is offline")) {
      console.error("Please check your Firebase configuration.");
    }
  }
}
testConnection();

// Structured Error Handling as per Firebase Integration Skill guidelines
export enum OperationType {
  CREATE = "create",
  UPDATE = "update",
  DELETE = "delete",
  LIST = "list",
  GET = "get",
  WRITE = "write"
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
  };
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid || null,
      email: auth.currentUser?.email || null,
      emailVerified: auth.currentUser?.emailVerified || null,
      isAnonymous: auth.currentUser?.isAnonymous || null,
      tenantId: auth.currentUser?.tenantId || null
    },
    operationType,
    path
  };
  console.error("Firestore Error: ", JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

export interface CloudStorageService {
  saveSession(session: InterviewSession): Promise<void>;
  getSession(id: string): Promise<InterviewSession | null>;
  getAllSessions(): Promise<InterviewSession[]>;
  deleteSession(id: string): Promise<void>;
}

export class FirestoreStorageService implements CloudStorageService {
  async saveSession(session: InterviewSession): Promise<void> {
    const path = `sessions/${session.id}`;
    try {
      const docRef = doc(db, "sessions", session.id);
      await setDoc(docRef, JSON.parse(JSON.stringify(session)));
    } catch (e) {
      handleFirestoreError(e, OperationType.WRITE, path);
    }
  }

  async getSession(id: string): Promise<InterviewSession | null> {
    const path = `sessions/${id}`;
    try {
      const docRef = doc(db, "sessions", id);
      const snapshot = await getDoc(docRef);
      if (snapshot.exists()) {
        return snapshot.data() as InterviewSession;
      }
    } catch (e) {
      handleFirestoreError(e, OperationType.GET, path);
    }
    return null;
  }

  async getAllSessions(): Promise<InterviewSession[]> {
    const path = "sessions";
    try {
      const collRef = collection(db, "sessions");
      const q = query(collRef, orderBy("startTime", "desc"));
      const snapshot = await getDocs(q);
      const list: InterviewSession[] = [];
      snapshot.forEach((d) => {
        list.push(d.data() as InterviewSession);
      });
      return list;
    } catch (e) {
      handleFirestoreError(e, OperationType.LIST, path);
      return [];
    }
  }

  async deleteSession(id: string): Promise<void> {
    const path = `sessions/${id}`;
    try {
      const docRef = doc(db, "sessions", id);
      await deleteDoc(docRef);
    } catch (e) {
      handleFirestoreError(e, OperationType.DELETE, path);
    }
  }
}

export async function getUserProfile(uid: string): Promise<UserProfile | null> {
  const path = `users/${uid}`;
  try {
    const docRef = doc(db, "users", uid);
    const snapshot = await getDoc(docRef);
    if (snapshot.exists()) {
      return snapshot.data() as UserProfile;
    }
  } catch (e) {
    handleFirestoreError(e, OperationType.GET, path);
  }
  return null;
}

export async function saveUserProfile(profile: UserProfile): Promise<void> {
  const path = `users/${profile.uid}`;
  try {
    const docRef = doc(db, "users", profile.uid);
    await setDoc(docRef, JSON.parse(JSON.stringify(profile)));
  } catch (e) {
    handleFirestoreError(e, OperationType.WRITE, path);
  }
}

export async function getLeaderboard(): Promise<UserProfile[]> {
  const path = "users";
  try {
    const collRef = collection(db, "users");
    const q = query(collRef, orderBy("totalScore", "desc"), limit(20));
    const snapshot = await getDocs(q);
    const list: UserProfile[] = [];
    snapshot.forEach((d) => {
      list.push(d.data() as UserProfile);
    });
    return list;
  } catch (e) {
    handleFirestoreError(e, OperationType.LIST, path);
    return [];
  }
}
